name: Seth Test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19762
title: Testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.8166072564199567
purpose: []
