name: Seth Test
favicon: null
layout_spectrum: 0.52601
typography_spectrum: 0.19762
title: Testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5e2ff'
    - '#000035'
    - '#002f7b'
    - '#0061b7'
    - '#69ace2'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.8166072564199567
purpose: []
