typography_spectrum: 0.91438
color:
  brandColors:
    - '#effffc'
    - '#8a6e58'
    - '#0e0e0c'
    - '#c0a280'
    - '#67b158'
  brandStrength: 1
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.52601
analytics:
  google: null
  facebook: null
  twitter: null
name: Seth Test
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hello
purpose: []
